# Generated by Django 2.1.2 on 2019-05-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='plates',
            field=models.ManyToManyField(to='Order.Plate'),
        ),
    ]
