# Generated by Django 2.1.2 on 2019-05-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHasPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.Order')),
                ('plate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.Plate')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='plates',
            field=models.ManyToManyField(through='Order.OrderHasPlate', to='Order.Plate'),
        ),
    ]
