# Generated by Django 2.1.2 on 2019-05-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_auto_20190526_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhasplate',
            old_name='preco',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='orderhasplate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Order.Order'),
        ),
        migrations.AlterField(
            model_name='orderhasplate',
            name='plate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate', to='Order.Plate'),
        ),
    ]
