# Generated by Django 2.1.2 on 2019-05-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_auto_20190526_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderhasplate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.Order'),
        ),
        migrations.AlterField(
            model_name='orderhasplate',
            name='plate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.Plate'),
        ),
    ]
