# Generated by Django 2.1.2 on 2019-05-28 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_auto_20190527_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('since', models.DateTimeField(auto_now=True)),
                ('end_period', models.DateTimeField(default=None, null=True)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.Plate')),
            ],
        ),
    ]
