# Generated by Django 2.1.2 on 2019-05-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_platecost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platecost',
            name='end_period',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
