# Generated by Django 2.1.2 on 2019-05-28 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_auto_20190528_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='cost',
        ),
    ]
